apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: deskship
spec:
  replicas: 2
  selector:
    matchLabels:
      deskship: frontend
  template:
    metadata:
      labels:
        deskship: frontend
    spec:
      containers:
      - name: frontend
        image: us-west1-docker.pkg.dev/data-oasis-342809/deskship/deskship-frontend:latest
        ports:
        - containerPort: 80