apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fronend-ingress
  namespace: deskship
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80
  ingressClassName: nginx

  tls:
    - hosts:
      - deskship.leycura.de