apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: deskship
  labels:
    role: frontend
spec:
  type: NodePort
  selector:
    role: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000