apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: deskship
spec:
  replicas: 2
  selector:
    matchLabels:
      deskship: backend
  template:
    metadata:
      labels:
        deskship: backend
    spec:
      containers:
        - name: backend
          image: us-west1-docker.pkg.dev/data-oasis-342809/deskship/deskship-backend:latest
          ports:
            - containerPort: 8000