apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: deskship
spec:
  externalName: postgres
  type: LoadBalancer
  selector:
    deskship: postgres
  ports:
    - port: 5432
      targetPort: 5432