apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-service
  selector:
    matchLabels:
      deskship: postgres
  replicas: 2
  template:
    metadata:
      labels:
        deskship: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          volumeMounts:
            - name: postgres-disk
              mountPath: /data
          env:
            - name: POSTGRES_USER
              value: "leycura"
            - name: POSTGRES_PASSWORD
              value: "Test123!"
            - name: PGDATA
              value: /data/pgdata
# Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgres-disk
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi